/**
 * package.json is the single source of truth for the version. It has to appear
 * in two other places that cannot read it at runtime — manifest.json (consumed
 * by Claude Desktop) and the MCP server identity (esbuild inlines the server
 * into a bundle that ships no package.json) — so this script stamps both.
 *
 * Runs automatically on `npm run build`; `test/version.test.ts` fails if the
 * three ever disagree, so a forgotten sync cannot reach a release.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const version: string = pkg.version;

const manifestPath = resolve(root, "manifest.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
manifest.version = version;
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n");

writeFileSync(
  resolve(root, "src/version.ts"),
  `// Generated by scripts/sync-version.ts from package.json — do not edit.\n` +
    `export const VERSION = ${JSON.stringify(version)};\n`,
);

console.error(`synced version ${version} into manifest.json and src/version.ts`);
